<%
local brand = "LPP"
local title = brand
local requirements = {
    "Lua",
    "C++17",
    "CMake to build it"
}
%>

<? "header.inc.lpp" ?>

<div class="container content">

<h1><%= brand %></h1>

<p>A minimal Lua templates engine. Emits regular Lua code.</p>
<p>It is a bit like PHP, but without PHP.</p>

<h2>License</h2>

<p>MIT</p>

<h2>Requirements</h2>
<ul>
<% for i = 1, #requirements do %>
  <li><%= requirements[i] %></li>
<% end %>
</ul>

<!-- Include once -->
<?# "samples.inc.lpp" ?>
<?# "samples.inc.lpp" ?>

<h2>Usage</h2>

<pre>$ lpp &lt;filename&gt;</pre>

</div>

<? "footer.inc.lpp" ?>
